# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Lima CMS
            image:
        nav:
            - item_name: Pages and content
              item_url: '/pages'
            - item_name: Menus
              item_url: '/menus'
            - item_name: Configuration
              item_url: '#'
            - item_name: Languages and synchronisation
              item_url: '/synchronisation'
    footer:
        content:
            logo:
                text: Lima CMS
                image:
            copyright: Copyright &copy; 2019. - Copia Digital Ltd <br>All rights reserved.
        social_list:
            - network_name: facebook
              profile_url: '#'
            - network_name: twitter
              profile_url: '#'
            - network_name: instagram
              profile_url: '#'
            - network_name: youtube
              profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
